### ISSUE TITLE
Time cost of training

### ISSUE THREAD

**Issue by Zazexy** [vLAR-group/RayDF#2]
Hello, respect for your great work first!
I run `CUDA_VISIBLE_DEVICES=0 python run_cls.py --config configs/blender_cls.txt --scene lego` which cost nearly 3h with RTX4090 24G.
Is this time consumption normal?

**Comment by zhuomanliu** [comment]
Yes, the time consumption should be normal. Although we did not test on RTX 4090, we conducted experiments on RTX 3090, and the training of the Lego scene took about 4.5 hours.

**Comment by Zazexy** [comment]
Thank you so much！
