### ISSUE TITLE
How to get the visible results?

### ISSUE THREAD

**Issue by Zazexy** [vLAR-group/RayDF#3]
Hello!
I have finished running `sh run.sh 0 lego` and wandb shows successful. Are there any visible results I can get like rgb、depth or mesh?

**Comment by zhuomanliu** [comment]
Hi, Thanks for running our code! For visualization, you can refer to the **Evaluation** section in [README.md](https://github.com/vLAR-group/RayDF/blob/master/README.md), that is, running the following scripts:
```
CUDA_VISIBLE_DEVICES=0 python run_mv.py --config configs/blender.txt --scene lego --eval_only
# remove outliers
CUDA_VISIBLE_DEVICES=0 python run_mv.py --config configs/blender.txt --scene lego --eval_only --denoise
# compute surface normals
CUDA_VISIBLE_DEVICES=0 python run_mv.py --config configs/blender.txt --scene lego --eval_only --grad_normal
```

**Comment by Zazexy** [comment]
Thanks for your help!
