### ISSUE TITLE
Why using the dual-ray visibility classifier?

### ISSUE THREAD

**Issue by j-cyoung** [vLAR-group/RayDF#8]
Hi, thanks for your great work. 
Why using the dual-ray visibility classifier to train the ray-surface distance network(mv), since you have calculated all the dual-ray visibility results to train the classifier.

**Comment by zhuomanliu** [comment]
Thank you for your question.
When training the ray-surface distance network, we randomly sample the second ray (called _multi-view ray_ in the paper), **which may not be from the training set** (see Fig. 4 in the paper), to see if the second novel ray is visible/invisible with the primary ray. The well-trained classifier will be used here to provide a predicted visibility score for the second novel ray, thus leading the ray-surface distance network to learn the surface geometry.

**Comment by j-cyoung** [comment]
I see. Thanks for your reply. :+1: :-)

**Comment by saulgooodman** [comment]
Hello, I am also interested in this multi-view consistency classifier. I'd like to ask whether the entire system would completely collapse if the dual-ray visibility classifier is removed from the RayDF? I have removed the mv_input and mv_loss from the code, but I can still render a depth map. Can you provide specific experimental results regarding the removal of the multi-view consistency classifier? Thank you!

**Comment by zhuomanliu** [comment]
> Hello, I am also interested in this multi-view consistency classifier. I'd like to ask whether the entire system would completely collapse if the dual-ray visibility classifier is removed from the RayDF? I have removed the mv_input and mv_loss from the code, but I can still render a depth map. Can you provide specific experimental results regarding the removal of the multi-view consistency classifier? Thank you!

Hi, 
The dual-ray visibility classifier plays an important role in our RayDF to provide multiview consistency, so the RayDF w/o classifier will collapse. You can refer to the experimental results in **Table 5. (1) w/o classifier $h_\Phi$** and **Figure 8**, as well as discussions in **Sec. 4.5 and A.4.1** in the paper.

Thanks for your attention!
